### ISSUE TITLE
Omit snapshot on master branch

### ISSUE THREAD

**Issue by mikisseth** [sarhanm/gradle-versioner#18]
In our current Maven based development setup we use Atlassians jgitflow plugin to constantly update the Maven pom versions to correspond to the git branch model. I would very much like to switch to using Gradle and the gradler-versioner to avoid to updating hardcoded versions in the source code. 

The only remaining challenge is that when snapshots are enabled in the gradle-versioner plugin all versions are SNAPSHOT versions, including the master commits, which would have had NON-SNAPSHOT versions using classical mvn releases. It would therefore be great if it was possible to configure which branches should be excluded from being postfixed with -SNAPSHOT. Support branches might also be candidates from this exclusion.

**Comment by sarhanm** [comment]
Hey @mikisseth 

With the latest version ( >= 2.1.37 )  you should be able to do the following

```
apply plugin: 'com.sarhanm.versioner'
versioner{
    if( gitdata.branch != "master"  ) 
        snapshot=true
}
```

Let me know if this works for you and we can close this bug.

**Comment by mikisseth** [comment]
Nearly got me what I wanted. To get a clean master (release) version I also had to omit BranchMetadata. The end result was 
```
versioner {
    if (gitdata.branch != "master")
        snapshot = true
    else {
        omitBranchMetadata = true
    }
 }
```
Thanks for the help :-)
