### ISSUE TITLE
lightweight tags are not supported

### ISSUE THREAD

**Issue by icecrystal23** [sarhanm/gradle-versioner#31]
I am not sure if this is by design or not, but lightweight tags do not work correctly.  I discovered this while helping someone else dig into why their tag wasn't being picked up.  It came down to this command:

$ git describe --match v* --abbrev=0
fatal: No annotated tags can describe '3f37f599c1b4b04a84eb2fffc15419bb3a16814d'.
However, there were unannotated tags: try --tags.

$ git describe --match v* --abbrev=0 --tags
v0.20

It may be fixed by simply appending --tags to that command, if you want to support lightweight tags.

**Comment by sarhanm** [comment]
Should be easy enough. There are a couple of commands that would need the additional `--tags`.
