### ISSUE TITLE
branchEnvName is not used to read Environment variable

### ISSUE THREAD

**Issue by jiffle** [sarhanm/gradle-versioner#33]
Summary: setting the `branchEnvName` variable does not cause the contents of specified environment variable to be read.

To reproduce:
In `build.gradle.kts` add the following:
```
versioner {
    branchEnvName = "MY_BRANCH_NAME"
}
```

In shell run
`export MY_BRANCH_NAME="SomeTest"`
Then 
`gradle check`

Expected output:
`versioner:<group>:<name>=<version>.SomeTest.<sha>`
Actual output:
`versioner:<group>:<name>=<version>.master.<sha>`
 Version:
`3.0.13`

**Comment by sarhanm** [comment]
Thanks for the detailed issue report. 

The branchEnvName is not used if we can retrieve the git branch name via a git command. 

In other words, branchEnvName is only used when on a machine (typically a build machine) and the branch is either undefined or resolves to HEAD. 

Here is the relevent logic
https://github.com/sarhanm/gradle-versioner/blob/ff9bd5d7b430997c75240915e3a02eb8ba473fb9/src/main/groovy/com/sarhanm/versioner/Versioner.groovy#L175

Let me know if you have a use case that is blocked by this line of thinking.

**Comment by jiffle** [comment]
Thanks - yes, good point. 🤦‍♂️ 

The issue that I'm trying to resolve is that the branch is not resolving in GitLab CI (output branch is `unknown`) and the `branchEnvName` does not seem to be helping.
I was hoping that this trivial test case above would allow me to test it locally, but you're absolutely right about the expected behaviour.

I'll have another look at the behaviour in the CI environment
