### ISSUE TITLE
Build stuck on branch named "release/hotfix"

### ISSUE THREAD

**Issue by icecrystal23** [sarhanm/gradle-versioner#7]
Someone had a branch named "release/hotfix" and the gradle build got stuck forever.  I imagine it was probably stuck in this plugin (although I didn't debug it to be 100% sure).

We worked around the issue by renaming the branch.

**Comment by sarhanm** [comment]
Lots of changes have happened but i did write a couple of tests around this particular issue and the tests passed. So if it was a problem, it is now solved.
