### ISSUE TITLE
Not placing the code execution in afterEvaluate is causing early evaluation of gradle

### ISSUE THREAD

**Issue by sarhanm** [sarhanm/gradle-versioner#9]
Because we are trying too hard to make sure the versioner plugin executes as early as possible, we are accidently forcing gradle to evaluate the project well before its done initializing the build script. For example, we are retrieving the value from the properties container, which is putting the gradle project into a "configured" state which then prevents the project from adding pieces to the publishing plugin (amongst other things).

Solution: Move the execution into the afterEvaluate event. Worst case scenario, you'll have to grab the version of the project again during certain executions.

**Comment by sarhanm** [comment]
This caused more problems than its worth. We need to revert back to execution as soon as the plugin is applied. Configuring the project in an init.d file will have to wait until  https://issues.gradle.org/browse/GRADLE-2407 is resolved

**Comment by Alex-Vol-SV** [comment]
Have you considered changing versioner to be a class with a toString() method that is evaluated by Project when getVersion() is invoked? This trick may solve the problem of having to install the extension prior to applying the plugin. It may also eliminate the root of this problem as you would delay evaluation of the Versioner properties that is making the gradle project go into "configured" state.

Of course this also makes the GitData unavailable until the version is accessed. Perhaps a similar approach would work for GitData making it behave a bit like convention properties do.

**Comment by sarhanm** [comment]
I'm not sure if that works because we are at the whim of other plugins who might pull in the version string. The current usage of this plugin at Zillow is using the GitData in the build logic of build.gradle and therefore needing the actual version metadata early enough continues to be a forcing function. In the various projects we have so far, i have yet to use the VersionerOptions extensibly. We like our versions to always be fully defined regardless of branch (makes hotfixing easier) and think thats a better practice then clean version numbers. The only exception here is for android, ios and gradle plugin builds that enforce a version scheme for uploads to their stores/repos. Adding the VersionerOptions extensions manually is a small inconvenience that we are willing to live with.

**Comment by Alex-Vol-SV** [comment]
Check out how I implemented this logic in my new pull request. GitData is a lazy evaluation extension that will return the data on demand instead of getting eagerly populated. It is working great in my build scripts. I use both the project.version and gitdata in scripts without issues.

**Comment by Alex-Vol-SV** [comment]
I have reached the same conclusion regarding versions on branches. I make the solidBranchREgex = .* for my builds so regardless of branch the version is always defined in a consistent manner.

Thank you for a great plugin by the way!

**Comment by sarhanm** [comment]
ah, now i see why you want the VersionerOptions in a more natural way. i
wonder if we should just make the .* the default. It would allow the
version ranges functionality to be a bit more specific too i think. i would
need to talk to others at zillow first because this would be a breaking
change for our current set of version ranges used by some devs.
